mv/Controllers/RateController.cs
using mv.DataModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mv.Controllers
{
    public class RateController : Controller
    {
        DataModel.Model1 ent = new DataModel.Model1();
        // GET: Rate
        public ActionResult Index()
        {
            int userID = 6;
            var raters = (from r in ent.RateUserRelations
                          where r.UserID == userID
                          select r.RateID).ToList();
            var rate = (from rt in ent.Rates
                        where !(raters.Contains(rt.ID)) && rt.UserID != userID
                        orderby Guid.NewGuid()
                        select rt).FirstOrDefault();
            if (rate != null)
            {
                return View(rate);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        public ActionResult Rating(int rateID)
        {
            RateUserRelations r = new RateUserRelations();
            r.RateID = rateID;
            r.UserID = 6;
            double rate = Convert.ToDouble(ViewBag.rate);
            var ratee = (from rt in ent.Rates
                         where rt.ID == rateID
                         select rt).FirstOrDefault();
            ratee.StarPoint = ratee.StarPoint + (Convert.ToDouble(Request.Form["rate"]) / 10);
            ratee.RateCount = ratee.RateCount + 1;
            ent.RateUserRelations.Add(r);
            try
            {
                ent.SaveChanges();
            }
            catch (Exception ex)
            {
                string hata = ex.Message;
            }
            return RedirectToAction("Index");
        }

        public ActionResult ShareRate()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult ShareRate(string p)
        {
            Rates r = new Rates();
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                if (file != null)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/ratePics"), fileName);
                    file.SaveAs(path);
                    r.PictureLoc = "~/Content/ratePics/" + fileName;
                    Users u = (Users)Session["KullaniciLogin"];
                    r.DateTime = DateTime.Now;
                    r.UserID = u.ID;
                    r.StarPoint = 0;
                    r.RateCount = 0;
                }
            }
            ent.Rates.Add(r);
            try
            {
                ent.SaveChanges();
            }
            catch (Exception ex)
            {
                string hata = ex.Message;
            }

            return RedirectToAction("Index","ProfilePage");

        }
    }
}

mv/Views/Rate/Index.cshtml
@model mv.DataModel.Rates

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    double sp = Model.StarPoint;
    int rc = Model.RateCount;
    double rt = sp / rc;
    string sonuc = rt.ToString();
    if (rt.ToString().Length > 1)
    {
        rt = Math.Round(rt, 2);
        string[] rr = rt.ToString().Split(',');
        sonuc = rr[0] + '.' + rr[1];
    }

}
<head>
    <link href="~/Content/star-rating.css" rel="stylesheet" media="all" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <script src="~/Scripts/star-rating.min.js" type="text/javascript"></script>
</head>
@using (Html.BeginForm("Rating", "Rate", FormMethod.Post))
{
    @Html.ActionLink("blala", "ShareRate","Rate")
    <div class="panel panel-primary" style="width:500px; height:680px; margin:auto; margin-top:50px">
        <div class="panel-heading">
            <h3 class="panel-title">@Model.Users.Name</h3>
        </div>
        <div class="panel-body">
            <div style="float:left">
                <img src='@Url.Content(Model.PictureLoc)' alt='p' width="350px" height="450px" />
            </div>
            <div style="float:left; margin-left:30px; margin-top:100px">
                <ul id="tik" class="pagination pagination-lg">
                    <input id="btnNext" type="submit" value="&raquo;" class="btn btn-success" />
                </ul>
            </div>
            <div style="clear:both">
                <input name="rateID" value="@Model.ID" id="Text1" type="hidden" />
                <input name="rate" id="rate" value="@sonuc" type="number" class="rating" min=0 max=5 step=0.1 data-rtl=1 data-container-class='text-right' data-glyphicon=0>
            </div>
        </div>
    </div>
}

mv/Views/Rate/Rating.cshtml
@{
    ViewBag.Title = "Rating";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Rating</h2>

mv/Views/Rate/ShareRate.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ShareRate", "Rate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <div class="col-md-12">
            <input type="file"  name="FileUpload2" accept="image/*" onchange="loadFile(event)" class="btn btn-default">
            <img id="output" style="max-width:250px; max-height:250px" />
            <script>
                var loadFile = function (event) {
                    var reader = new FileReader();
                    reader.onload = function () {
                        var output = document.getElementById('output');
                        output.src = reader.result;
                    };
                    reader.readAsDataURL(event.target.files[0]);
                };
            </script>

        </div>
        <div class="col-md-12">
            <input type="submit" value=@mv.Views.Resources.Share class="btn btn-default" />
        </div>
    </div>
}